input {
  beats {
    port => 5044
  }
}

filter {
  if [kubernetes][namespace] {
    mutate {
      add_field => { "portfolio_environment" => "%{[kubernetes][namespace]}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "portfolio-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
