apiVersion: v1
kind: Secret
metadata:
  name: portfolio-mysql
  namespace: portfolio
type: Opaque
stringData:
  host: portfolio-prod-mysql.xxxxxxxxxxxx.us-east-1.rds.amazonaws.com
  database: portfolio
  username: portfolio_admin
  password: replace-with-rds-password
