apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: portfolio-dev
nameSuffix: -dev
resources:
  - ../../base
patches:
  - target:
      kind: Namespace
      name: portfolio
    patch: |-
      - op: replace
        path: /metadata/name
        value: portfolio-dev
  - target:
      kind: Deployment
      name: portfolio-web
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Ingress
      name: portfolio-web
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev.portfolio.example.com
  - target:
      kind: Deployment
      name: portfolio-web
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/valueFrom/secretKeyRef/name
        value: portfolio-mysql-dev
      - op: replace
        path: /spec/template/spec/containers/0/env/1/valueFrom/secretKeyRef/name
        value: portfolio-mysql-dev
      - op: replace
        path: /spec/template/spec/containers/0/env/2/valueFrom/secretKeyRef/name
        value: portfolio-mysql-dev
images:
  - name: ghcr.io/your-github-user/devops-portfolio
    newTag: dev
